config/routes.rb
Rails.application.routes.draw do

  resources :link_attachments, only: [:destroy]
  resources :attachments, only: [:create,:destroy,:new,:show]
  resources :products
  resources :in_shopping_carts, only: [:create,:destroy]
  devise_for :users
  
  post "/emails/create", as: :create_email
  post "/pagar", to: "payments#create"
  post "/payments/cards", to: "payments#process_card"
  
  get "/carrito", to: "shopping_carts#show"
  get "/add/:product_id", as: :add_to_cart,to: "in_shopping_carts#create"
  get "/checkout",to: "payments#checkout"
  
  get "/descargar/:id", to: "links#download"
  get "/descargar/:id/archivo/:attachment_id", to: "links#download_attachment", as: :download_attachment
  get "invalid", to: "welcome#unregistered"
  
  get "/ok", to: "welcome#payment_succed"
  
  get "/ordenes", to: "ordenes#index"
  

  authenticated :user do
    root 'welcome#index'
  end
  
  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end  

end

app/views/partials/_nav.haml
%header
  %nav.green  
    %ul.no-list.no-padding.text-center.white-text   
      %li.col-md-4.inline-block.tall-padding.pull-left         
        -if user_signed_in?
          =link_to root_path, class:"right-space white-text" do
            %i.mdi-action-star-rate
            Mi tienda       
          =link_to edit_user_registration_path, class:"right-space white-text" do
            %i.mdi-image-control-point
            Editar Perfil          
          =link_to destroy_user_session_path, method: :delete, class:"right-space white-text" do
            %i.mdi-maps-pin-drop
            Cerrar sesión
      %li.col-md-2.inline-block.text-center
        =image_tag "tiendus.png", height:"25px"
      %li.col-md-4.inline-block.tall-padding
        =link_to products_path, class:"right-space white-text" do
          %i.mdi-action-view-day
          Productos       
        =link_to carrito_path, class:"white-text" do
          %i.mdi-action-shop-two
          Mi carrito
          (
          = @shopping_cart.products.length
          )