config/routes.rb
Rails.application.routes.draw do

  resources :link_attachments, only: [:destroy]
  resources :attachments, only: [:create,:destroy,:new,:show]
  resources :products
  resources :in_shopping_carts, only: [:create,:destroy]
  devise_for :users
  
  post "/emails/create", as: :create_email
  post "/pagar", to: "payments#create"
  post "/payments/cards", to: "payments#process_card"
  
  get "/carrito", to: "shopping_carts#show"
  get "/add/:product_id", as: :add_to_cart,to: "in_shopping_carts#create"
  get "/checkout",to: "payments#checkout"
  
  get "/descargar/:id", to: "links#download"
  get "/descargar/:id/archivo/:attachment_id", to: "links#download_attachment", as: :download_attachment
  get "invalid", to: "welcome#unregistered"
  
  get "/ok", to: "welcome#payment_succed"
  
  get "/ordenes", to: "ordenes#index"
  

  authenticated :user do
    root 'welcome#index'
  end
  
  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end  

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  name                :string
#  pricing             :integer
#  description         :text
#  user_id             :integer
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Product < ActiveRecord::Base
  belongs_to :user
  has_many :attachments, dependent: :destroy
  has_many :in_shopping_carts, dependent: :destroy
  has_one :shopping_cart, through: :in_shopping_carts
  has_many :my_payments, through: :shopping_cart
  has_many :links, dependent: :destroy
  validates_presence_of :name, :user, :pricing
  validates :pricing, numericality: { greater_than: 0}
  has_attached_file :avatar, styles: { medium: "300x300", thumb:"100x100" }, default_url: "missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
  def self.search(search)
    where("name ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%") 
  end
  
  def paypal_form
    {name: name,sku: :item, price: (pricing),currency:"USD",quantity:1}
  end
  
  def sales
    my_payments.payed
  end
  
  def sales_total
    my_payments.payed.count * self.pricing
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!,except: [:index,:show]
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    if params[:search]
      @products = Product.search(params[:search]).order("created_at DESC")
    else
      @products = Product.all.order('created_at DESC')
    end
  end  

  # GET /products/1
  # GET /products/1.json
  def show
    if user_signed_in? && current_user == @product.user && !params.has_key?(:client)
      @attachment = Attachment.new
      render :admin
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Producto creado con exito.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Producto editado con exito.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    
    @attachment = Attachment.where(product_id: params[:id])
    if @attachment
      #@attachment.destroy_all
      @linkattachment = LinkAttachment.where(attachment_id: @attachment)
      @linkattachment.destroy_all
    end

    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Producto eliminado con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :pricing, :description, :avatar)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product,builder: BootstrapFormBuilder do |f|
  = f.errors
  .row.top-space
    .col-md-6.col-xs-12
      = f.text_field(:name, "xd")
    .col-md-6.col-xs-12
      = f.text_field :pricing
      %small Precio en Dolares.
  .row.top-space
    .col-xs-12
      = f.text_area :description
  .row.top-space
    .col-xs-8.center-block.no-float.text-center
      = f.file_field :avatar
      %small Portada producto.
  .text-right.top-space
    = f.submit "Agregar"

app/views/products/_product.haml
%article.top-space
  .large-padding.text-left
    .col-md-3.inline-block.no-padding
    .col-md-9.inline-block.no-padding.text-right
      - if product.sales.count > 0
        ="#{product.sales.count}" + " Ventas = $"    
        = product.sales_total
        USD
      -else
        No ha tenido ventas.
  %h3.large-padding.red.white-text.no-margin
    = link_to product.name,product,class:"white-text"

app/views/products/admin.haml
.col-md-3.no-padding.inline-block.in-top
  %nav.medium
    .green.white-text.col-md.12.small-padding
      Admin general
.col-md-9.inline-block.in-top
  .card.large-padding
    .col-md-9.inline-block
      %h1= @product.name
    .col-md-3.inline-block
      %p.big.no-margin.red-text
        =@product.sales_total
        USD
    %nav.top-space
      =link_to product_path(id: @product.id, client:true), class:"other-grey large-padding text-center col-md-4 inline-block" do
        Ver como cliente
      =link_to edit_product_path(@product), class:"other-grey large-padding text-center col-md-4 inline-block" do
        Editar producto
      =link_to @product,method: :delete, class:"other-grey large-padding text-center col-md-4 inline-block", data: { confirm: "¿Estás seguro de eliminar el producto?" } do
        Eliminar producto
    %div
      %h3.grey-text Archivos
      %ol
        -@product.attachments.each do |attachment|
          %li.large-padding.medium.grey-text.other-grey
            .col-xs-11.inline-block= link_to attachment.archivo_file_name, attachment, target:"_blank"
            .col.xs-1.inline-block
              =link_to attachment, method: :delete, data: { confirm: "¿Estás seguro de eliminar el archivo?" },class:"red-text" do
                %i.mdi-action-dashboard
      =render "attachments/form", product_id: @product.id

app/views/products/edit.html.haml
.col-md-6.col-xs-10.col-sm-8.col-lg-5.no-float.center-block
  .card.big-padding.big-top-space
    %h1 Editar producto
    = render 'form'

app/views/products/index.html.haml
%h1 Lista de Productos
= form_tag(products_path, :method => "get", id: "search-form") do
  .form-group.big-top-space
    = text_field_tag :search, params[:search], placeholder: "Buscar un producto", class: "form-control"
    .text-right
      = submit_tag "Buscar", class: "btn btn-success"
%hr
- @products.each do |product|
  .col-sm-6.col-md-3.top-space
    .card.top-space
      .img-cont
        =image_tag product.avatar.url, class:"card-img-top img-rounded", style: "max-height: 200px; margin: 2em auto 0 auto; display:block"
      .big-padding
        %h4.bold.card-title= product.name
        %p
          $
          = product.pricing
        %hr
        .card-action.text-center
          = link_to 'Ver', product_path(id: product.id, client:true), class: "btn btn-info"
          = render "in_shopping_carts/form",product: product

app/views/products/new.html.haml
.col-md-6.col-xs-10.col-sm-8.col-lg-5.no-float.center-block
  .card.big-padding.big-top-space
    %h1 Agregar producto
    = render 'form'

app/views/products/show.html.haml
.col-lg-7.col-md-8.col-xs-12.col-sm-10.no-float.center-block
  %article.card.big-padding
    %header
      %h1.grey-text.bold= @product.name
    %section
      .col-xs-6.col-md-5.no-padding.inline-block
        =image_tag @product.avatar.url
      .col-md-1.inline-block.hidden-xs
      .col-xs-5.col-md-6.inline-block.text-left
        %h3.blue-text.bold.normal= @product.user.email
        %h3.teal-text.bold.normal
          Precio:
          %span.grey-text= "$#{@product.pricing}" 
        %h3.teal-text.bold.normal
          Archivos:
          %span.grey-text= "#{@product.attachments.count}"
        =render "in_shopping_carts/form",product: @product
    %section
      %h3.green-text.bold.normal Descripción
      %p= @product.description